version: '3.8'

services:
  web:
    build: .
    container_name: mushqila_web
    ports:
      - "80:8000"
    env_file:
      - .env.production
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - mushqila_network

  redis:
    image: redis:7-alpine
    container_name: mushqila_redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - mushqila_network

  celery:
    build: .
    container_name: mushqila_celery
    command: celery -A config worker -l info
    env_file:
      - .env.production
    depends_on:
      - redis
      - web
    restart: unless-stopped
    networks:
      - mushqila_network

  celery-beat:
    build: .
    container_name: mushqila_celery_beat
    command: celery -A config beat -l info
    env_file:
      - .env.production
    depends_on:
      - redis
      - web
    restart: unless-stopped
    networks:
      - mushqila_network

volumes:
  static_volume:
  media_volume:

networks:
  mushqila_network:
    driver: bridge